jobs:
  sakai-deploy:
    env:
      JAVA_OPTS: -Dhttp.agent=Sakai -Xms2512m -Xmx2512m -Dsakai.cookieName=SAKAIID
        -Dorg.apache.jasper.compiler.Parser.STRICT_QUOTE_ESCAPING=false -Dsakai.demo=true
        -Djava.awt.headless=true --add-exports=java.base/jdk.internal.misc=ALL-UNNAMED
        --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=java.management/com.sun.jmx.mbeanserver=ALL-UNNAMED
        --add-exports=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED --add-exports=java.base/sun.reflect.generics.reflectiveObjects=ALL-UNNAMED
        --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED --illegal-access=permit
        -Dsakai.demo=true
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Git Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: JDK 11
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      env:
        MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
          -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Dmaven.wagon.http.retryHandler.count=2
          -Dmaven.wagon.http.pool=true
      name: Build with Maven
      run: "sudo systemctl start mysql.service\necho \"127.0.0.1 repository.dev.java.net\"\
        \ | sudo tee -a /etc/hosts\necho \"127.0.0.1 maven-repository.dev.java.net\"\
        \ | sudo tee -a /etc/hosts\necho \"127.0.0.1 maven2-repository.dev.java.net\"\
        \ | sudo tee -a /etc/hosts\nexport TOMCAT_DIR=$PWD/tomcat\nmkdir $TOMCAT_DIR\n\
        cd $TOMCAT_DIR\ncurl -s -o tomcat.tar.gz https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.87/bin/apache-tomcat-9.0.87.tar.gz\n\
        tar --strip-components=1 -xzf tomcat.tar.gz\ngit clone https://github.com/sakaiproject/nightly-config.git\
        \ sakai\ncp sakai/cypress.properties sakai/sakai.properties\nsed -i 's:<Context>:<Context><JarScanner><JarScanFilter\
        \ defaultPluggabilityScan=\"false\" /></JarScanner>:g' conf/context.xml\n\
        sed -i 's:<Service name=\"Catalina\">:<Service name=\"Catalina\"><Connector\
        \ port=\"8443\" protocol=\"org.apache.coyote.http11.Http11NioProtocol\" scheme=\"\
        https\" secure=\"true\" />:g' conf/server.xml\nmysql -u root -proot -e \"\
        create database sakai\"; \ncd ..\nmvn --batch-mode -DskipTests install sakai:deploy-exploded\
        \ -Dmaven.tomcat.home=$TOMCAT_DIR\ncd $TOMCAT_DIR\nbin/catalina.sh start\n\
        sleep 500s\ngrep \"Server startup in\" logs/catalina.out\n"
    - continue-on-error: true
      name: Start cloudflared
      run: 'curl -sL -o cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb

        sudo dpkg -i cloudflared.deb

        cloudflared tunnel --url http://localhost:8443 &

        '
    - continue-on-error: true
      name: Cypress Checkout
      uses: actions/checkout@v4
      with:
        path: ./cypress-sakai
        repository: sakaicontrib/cypress-sakai
    - continue-on-error: true
      env:
        COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
        CYPRESS_RECORD_KEY: f2049235-3f10-4142-a26c-fc017211a776
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Cypress Run
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        config: baseUrl=http://localhost:8080
        record: true
        wait-on: http://localhost:8080/portal/
        wait-on-timeout: 1800
        working-directory: cypress-sakai
    - continue-on-error: true
      if: always()
      name: Check number of MySQL statements
      run: 'export QUERIES=$(grep ProtocolLoggingProxy.info tomcat/logs/catalina.out|grep
        -v ROLLBACK|grep -v COMMIT | wc -l)

        echo "::notice title={MySQL Queries}::$QUERIES"

        '
    - continue-on-error: true
      if: always()
      name: Upload Tomcat log for review
      uses: actions/upload-artifact@v4
      with:
        name: tomcat-log
        path: tomcat/logs/catalina.out
        retention-days: 5
    - continue-on-error: true
      if: ${{ always() }}
      name: Sleep fifteen minutes to allow testing
      run: sleep 15m
name: Cypress E2E Browser Tests
on:
  repository_dispatch:
    types: trigger-ga___server.yml
