jobs:
  maven-build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Git Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: JDK 11
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.6
    - continue-on-error: true
      env:
        MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
          -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Dmaven.wagon.http.retryHandler.count=2
          -Dmaven.wagon.http.pool=true
      name: Build with Maven
      run: mvn --show-version --batch-mode -PskipBrokenTests test
name: Windows Build
on:
  repository_dispatch:
    types: trigger-ga___windows.yml
